services:
  - type: web
    name: intelect-marine
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
    branches:
      - main
    envVars:
      - key: FLASK_ENV
        value: production